"""
edgar_client.py — a thin, defensive wrapper around the SEC EDGAR REST APIs.

Design notes for whoever picks this up cold:
  * This module holds ALL the EDGAR logic. server.py is a thin MCP shim on top,
    so the same functions can be unit-tested and reused off-server (the sample
    memo is generated by calling these directly, and the test suite drives them
    against recorded fixtures with no network).
  * Every financial datapoint carries its provenance: the accession number of
    the filing it came from and a resolvable EDGAR URL. Attribution is
    structural, not decorative — see `SourcedValue`.
  * EDGAR is an "imperfect vendor system": tags vary by company, values are
    restated, sections are messy HTML. We fail soft and say so rather than
    guessing.
  * JUDGMENT LIVES IN CODE. Ratio meaningfulness (negative/near-zero
    denominators) and red-flag detection are computed here and returned as
    structured objects. The model narrates them; it does not decide them.

Fetch strategy:
  * One `companyfacts` call per company gives us EVERY XBRL fact the filer has
    ever reported. We fetch it once, cache it, and slice locally. The earlier
    design issued one `companyconcept` call per line item (~17 per screen, and
    twice over when metrics and financials were both requested).

SEC fair-access rules (learned the hard way — a missing header returns HTTP 403):
  * A descriptive User-Agent with contact info is REQUIRED. Set EDGAR_USER_AGENT.
  * Stay under ~10 requests/second. We self-throttle and back off on 429/5xx.
"""

from __future__ import annotations

import logging
import os
import re
import threading
import time
from dataclasses import asdict, dataclass
from typing import Any, Optional

import warnings

import requests
from bs4 import BeautifulSoup, XMLParsedAsHTMLWarning

# Some EDGAR primary documents are inline-XBRL/XML; we parse them leniently as
# HTML on purpose. Silence the (benign) advisory warning.
warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

log = logging.getLogger("northbridge.edgar")

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #

# SEC requires a real contact in the UA string. Override via env in production.
USER_AGENT = os.environ.get(
    "EDGAR_USER_AGENT", "Northbridge Diligence Tool contact@example.com"
)
_MIN_INTERVAL = 0.12   # ~8 req/s, comfortably under the 10 req/s ceiling
_TIMEOUT = 20
_MAX_RETRIES = 3       # on 429 / 5xx only
_CACHE_TTL = 3600      # seconds; a filing does not change within an hour
_CACHE_MAX = 64        # bounded so a long-lived server does not grow forever

# How we resolve a period reported more than once (original 10-K vs. the
# comparative column of a later 10-K). Explicit, not accidental.
RESTATEMENT_POLICY = "as_last_reported"   # | "as_originally_reported"

# Screening thresholds, in one place so they are reviewable and testable.
THRESHOLDS = {
    "current_ratio_low": 1.0,
    "debt_to_ebitda_high": 4.0,
    "interest_coverage_low": 2.0,
    "revenue_decline_pct": -0.05,
    "stale_data_months": 15,
    # A denominator smaller than this fraction of the numerator makes the
    # ratio arithmetically valid but analytically meaningless.
    "near_zero_denominator_ratio": 0.01,
}

_session = requests.Session()
_session.headers.update({"User-Agent": USER_AGENT, "Accept-Encoding": "gzip, deflate"})
_last_call = [0.0]
_lock = threading.Lock()

# Simple request counter — the cheapest useful observability there is.
STATS = {"requests": 0, "cache_hits": 0, "retries": 0}


class EdgarError(Exception):
    """Base class for expected, user-facing failures.

    Every error carries a machine-readable taxonomy, because a model deciding
    what to do next needs more than prose. The distinction that matters most:

      * ``recoverable`` — "the model can continue its turn". True for anything a
        model can narrate around, which is nearly everything: a bad ticker means
        ask the user, a data gap means report the gap. False only for genuine
        internal faults, where continuing would mean inventing something.
      * ``retryable`` — "issuing this exact call again may succeed". True only
        for transient conditions: rate limits, upstream 5xx, network blips.

    Those two are independent and both useful. A 404 on a bad ticker is
    recoverable (ask the user which company they meant) but not retryable
    (calling again returns the same 404). A 429 is both. Collapsing them, which
    the first version of this envelope did by hardcoding ``recoverable: True``,
    left the model unable to tell a permanent failure from a transient one.

    Subclasses set ``code`` and the taxonomy; ``retry_after_seconds`` is filled
    in from EDGAR's ``Retry-After`` header when the upstream sends one.
    """

    code: str = "INTERNAL"
    category: str = "internal"
    retryable: bool = False
    recoverable: bool = True

    def __init__(self, message: str, *, retry_after_seconds: float | None = None,
                 **extra: Any):
        super().__init__(message)
        self.retry_after_seconds = retry_after_seconds
        self.extra = extra

    def envelope(self) -> dict:
        """The dict a tool returns for this error.

        ``error`` and ``recoverable`` are kept exactly as the original envelope
        had them: SKILL.md instructs the model on that shape and the golden
        snapshots capture it, so the new fields are additive.
        """
        payload = {
            "error": str(self),
            "recoverable": self.recoverable,
            "code": self.code,
            "category": self.category,
            "retryable": self.retryable,
        }
        if self.retry_after_seconds is not None:
            payload["retry_after_seconds"] = self.retry_after_seconds
        payload.update(self.extra)
        return payload


class InvalidArgument(EdgarError):
    """Caller passed something the tool cannot act on (bad years, bad limit)."""

    code = "INVALID_ARGUMENT"
    category = "client_error"


class CompanyNotFound(EdgarError):
    """No SEC registrant matches the query. Permanent for this query."""

    code = "COMPANY_NOT_FOUND"
    category = "client_error"


class InvalidTag(EdgarError):
    """A malformed or non-existent XBRL tag was requested."""

    code = "INVALID_TAG"
    category = "client_error"


class NoXBRLData(EdgarError):
    """The filer exists but reports no usable US-GAAP XBRL facts.

    A data gap rather than a client error: the request was well-formed and
    EDGAR answered honestly. Foreign private issuers filing 20-F under IFRS are
    the common case.
    """

    code = "NO_XBRL_DATA"
    category = "data_gap"


class SectionNotFound(EdgarError):
    """A filing section could not be isolated from the document."""

    code = "SECTION_NOT_FOUND"
    category = "data_gap"


class RateLimited(EdgarError):
    """SEC is throttling us. Transient by definition."""

    code = "RATE_LIMITED"
    category = "upstream_error"
    retryable = True


class UpstreamUnavailable(EdgarError):
    """EDGAR failed in a way that may not recur: 5xx, timeout, connection reset."""

    code = "UPSTREAM_UNAVAILABLE"
    category = "upstream_error"
    retryable = True


# --------------------------------------------------------------------------- #
# HTTP: throttle, retry, bounded TTL cache
# --------------------------------------------------------------------------- #

class _TTLCache:
    """Tiny bounded TTL cache. Enough for a session-scoped MCP server; a real
    deployment would swap this for Redis or a disk cache without touching
    callers."""

    def __init__(self, maxsize: int = _CACHE_MAX, ttl: int = _CACHE_TTL):
        self._data: dict[str, tuple[float, Any]] = {}
        self._maxsize = maxsize
        self._ttl = ttl
        self._lock = threading.Lock()

    def get(self, key: str) -> Optional[Any]:
        with self._lock:
            hit = self._data.get(key)
            if not hit:
                return None
            stamped, value = hit
            if time.monotonic() - stamped > self._ttl:
                self._data.pop(key, None)
                return None
            STATS["cache_hits"] += 1
            return value

    def put(self, key: str, value: Any) -> None:
        with self._lock:
            if len(self._data) >= self._maxsize:
                oldest = min(self._data, key=lambda k: self._data[k][0])
                self._data.pop(oldest, None)
            self._data[key] = (time.monotonic(), value)

    def clear(self) -> None:
        with self._lock:
            self._data.clear()


_cache = _TTLCache()


def _throttle() -> None:
    with _lock:
        wait = _MIN_INTERVAL - (time.monotonic() - _last_call[0])
        if wait > 0:
            time.sleep(wait)
        _last_call[0] = time.monotonic()


def _retry_after(resp: requests.Response) -> float | None:
    """Parse EDGAR's Retry-After header, if it sent one.

    Worth surfacing rather than only sleeping on: once retries here are
    exhausted, the caller is told how long to wait before trying again instead
    of having to guess.
    """
    raw = (resp.headers.get("Retry-After") or "").strip()
    try:
        return float(raw) if raw else None
    except ValueError:
        return None  # HTTP-date form; we do not parse it, we just do not claim one


def _get(url: str) -> requests.Response:
    """GET with fair-access throttling and backoff on transient failures."""
    delay = 0.5
    last_retry_after: float | None = None
    for attempt in range(_MAX_RETRIES + 1):
        _throttle()
        STATS["requests"] += 1
        log.debug("GET %s (attempt %d)", url, attempt + 1)
        try:
            resp = _session.get(url, timeout=_TIMEOUT)
        except requests.RequestException as exc:
            if attempt < _MAX_RETRIES:
                STATS["retries"] += 1
                time.sleep(delay)
                delay *= 2
                continue
            raise UpstreamUnavailable(
                f"Network error contacting EDGAR ({url}): {exc}"
            ) from exc

        if resp.status_code == 200:
            return resp
        if resp.status_code == 403:
            # Not retryable: the header is wrong and will stay wrong until a
            # human fixes it. Retrying would just hammer EDGAR over our own bug.
            raise InvalidArgument(
                "EDGAR returned 403 Forbidden. Set a descriptive EDGAR_USER_AGENT "
                "with contact info (SEC fair-access policy requires it)."
            )
        if resp.status_code == 404:
            raise CompanyNotFound(f"EDGAR resource not found (404): {url}")
        # 429 / 5xx are transient — back off and retry.
        if resp.status_code in (429, 500, 502, 503, 504):
            last_retry_after = _retry_after(resp) or last_retry_after
            if attempt < _MAX_RETRIES:
                STATS["retries"] += 1
                sleep_for = last_retry_after if last_retry_after else delay
                log.warning("EDGAR %s on %s — retrying in %.1fs",
                            resp.status_code, url, sleep_for)
                time.sleep(sleep_for)
                delay *= 2
                continue
            # Retries exhausted. Distinguish throttling from a server fault so
            # the caller knows whether backing off further is likely to help.
            error = RateLimited if resp.status_code == 429 else UpstreamUnavailable
            raise error(
                f"EDGAR returned HTTP {resp.status_code} for {url} after "
                f"{_MAX_RETRIES + 1} attempts.",
                retry_after_seconds=last_retry_after,
            )
        raise UpstreamUnavailable(f"EDGAR returned HTTP {resp.status_code} for {url}")
    raise UpstreamUnavailable(f"EDGAR request failed after retries: {url}")


def _get_json(url: str) -> dict:
    cached = _cache.get(url)
    if cached is not None:
        return cached
    data = _get(url).json()
    _cache.put(url, data)
    return data


# --------------------------------------------------------------------------- #
# Provenance helpers
# --------------------------------------------------------------------------- #

def _accn_nodash(accn: str) -> str:
    return accn.replace("-", "")


def _filing_index_url(cik: int, accn: str) -> Optional[str]:
    """A resolvable link to the filing's index page (works for any accession)."""
    if not accn:
        return None
    return (
        f"https://www.sec.gov/Archives/edgar/data/{cik}/{_accn_nodash(accn)}/"
        f"{accn}-index.htm"
    )


def _document_url(cik: int, accn: str, primary_doc: str) -> str:
    return (
        f"https://www.sec.gov/Archives/edgar/data/{cik}/"
        f"{_accn_nodash(accn)}/{primary_doc}"
    )


@dataclass
class SourcedValue:
    """A single number that knows where it came from."""
    value: Optional[float]
    unit: str                     # e.g. "USD"
    period_end: Optional[str]     # e.g. "2024-09-28"
    fiscal_year: Optional[int]
    fiscal_period: Optional[str]  # "FY", "Q1", ...
    form: Optional[str]           # "10-K", "10-K/A"
    accession: Optional[str]
    source_url: Optional[str]
    xbrl_tag: Optional[str] = None
    filed: Optional[str] = None
    # Restatement transparency: set when an earlier filing reported a different
    # number for the same period.
    restated: bool = False
    originally_reported: Optional[float] = None

    def to_dict(self) -> dict:
        return asdict(self)


# --------------------------------------------------------------------------- #
# Company resolution (ticker / name -> CIK)
# --------------------------------------------------------------------------- #

def _load_ticker_map() -> list[dict]:
    cached = _cache.get("__tickers__")
    if cached is not None:
        return cached
    data = _get_json("https://www.sec.gov/files/company_tickers.json")
    rows = [
        {
            "cik": int(row["cik_str"]),
            "cik10": str(row["cik_str"]).zfill(10),
            "ticker": row["ticker"].upper(),
            "title": row["title"],
        }
        for row in data.values()
    ]
    _cache.put("__tickers__", rows)
    return rows


def _pub(row: dict) -> dict:
    return {
        "cik": row["cik"],
        "cik10": row["cik10"],
        "ticker": row["ticker"],
        "name": row["title"],
    }


def resolve_company(query: str, max_candidates: int = 5) -> dict:
    """
    Map a ticker or company name to a CIK.

    Returns {"resolved": {...}} on a confident match, or
            {"ambiguous": True, "candidates": [...]} when a name is ambiguous,
            so the caller/model can disambiguate rather than silently pick the
            wrong company.
    """
    if not query or not query.strip():
        raise InvalidArgument("Empty company query.")
    q = query.strip()
    rows = _load_ticker_map()

    # 1) Exact ticker match wins.
    exact = [r for r in rows if r["ticker"] == q.upper()]
    if exact:
        return {"resolved": _pub(exact[0])}

    # 2) Exact (case-insensitive) name match.
    ql = q.lower()
    name_exact = [r for r in rows if r["title"].lower() == ql]
    if len(name_exact) == 1:
        return {"resolved": _pub(name_exact[0])}

    # 3) Substring name match -> may be ambiguous.
    partial = [r for r in rows if ql in r["title"].lower()]
    if len(partial) == 1:
        return {"resolved": _pub(partial[0])}
    if len(partial) > 1:
        return {
            "ambiguous": True,
            "candidates": [_pub(r) for r in partial[:max_candidates]],
            "note": f"{len(partial)} companies matched '{query}'. "
                    "Pass a ticker or exact name to disambiguate.",
        }
    raise CompanyNotFound(
        f"No SEC-registered company matched '{query}'. "
        "Note: EDGAR only covers SEC filers (public/registered companies)."
    )


class AmbiguousCompany(EdgarError):
    """Raised when a data tool is handed a name that matches several filers.

    Carries the candidate list so the server layer can hand the model the same
    disambiguation payload `resolve_company` returns — the two paths agree.

    Not retryable: the same query returns the same ambiguity every time. It is
    resolved by the user picking a candidate, not by calling again.
    """

    code = "AMBIGUOUS_COMPANY"
    category = "client_error"

    def __init__(self, payload: dict):
        self.payload = payload
        super().__init__(payload.get("note", "Ambiguous company name."))

    def envelope(self) -> dict:
        # Candidates first, so the model reads the choice it has to offer the
        # user before the error framing around it.
        return {**self.payload, **super().envelope()}


def _resolve_cik(query: str) -> dict:
    """Internal: resolve to a single company or raise (used by data tools)."""
    res = resolve_company(query)
    if "resolved" in res:
        return res["resolved"]
    raise AmbiguousCompany(res)


# --------------------------------------------------------------------------- #
# Submissions (identity + filing history)
# --------------------------------------------------------------------------- #

def _get_submissions(cik10: str) -> dict:
    return _get_json(f"https://data.sec.gov/submissions/CIK{cik10}.json")


def get_company_profile(query: str) -> dict:
    comp = _resolve_cik(query)
    subs = _get_submissions(comp["cik10"])
    recent = subs.get("filings", {}).get("recent", {})

    latest = {}
    for want in ("10-K", "10-Q"):
        for i, form in enumerate(recent.get("form", [])):
            if form == want:
                latest[want] = {
                    "filed": recent["filingDate"][i],
                    "period": recent["reportDate"][i],
                    "accession": recent["accessionNumber"][i],
                    "url": _document_url(
                        comp["cik"], recent["accessionNumber"][i],
                        recent["primaryDocument"][i],
                    ),
                }
                break

    return {
        "cik": comp["cik"],
        "name": subs.get("name", comp["name"]),
        "tickers": subs.get("tickers", []),
        "exchanges": subs.get("exchanges", []),
        "sic": subs.get("sic"),
        "industry": subs.get("sicDescription"),
        "fiscal_year_end": subs.get("fiscalYearEnd"),
        "state": subs.get("stateOfIncorporation"),
        "latest_filings": latest,
        "source_url": (
            "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany"
            f"&CIK={comp['cik10']}&type=10-K"
        ),
    }


# --------------------------------------------------------------------------- #
# XBRL: one companyfacts fetch, sliced locally
# --------------------------------------------------------------------------- #

# Each screening line item maps to an ordered list of candidate US-GAAP tags,
# highest-preference first. We MERGE across them per fiscal year rather than
# taking the first tag that has any data: filers switch tags mid-history (the
# ASC 606 revenue transition is the classic case), and first-tag-wins silently
# truncates the series — usually dropping either the newest or the oldest years.
CONCEPT_MAP: dict[str, list[str]] = {
    "revenue": [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "Revenues",
        "RevenueFromContractWithCustomerIncludingAssessedTax",
        "SalesRevenueNet",
    ],
    "cost_of_revenue": [
        "CostOfRevenue", "CostOfGoodsAndServicesSold", "CostOfGoodsSold",
    ],
    "gross_profit": ["GrossProfit"],
    "operating_income": ["OperatingIncomeLoss"],
    "net_income": ["NetIncomeLoss", "ProfitLoss"],
    "total_assets": ["Assets"],
    "total_liabilities": ["Liabilities"],
    "current_assets": ["AssetsCurrent"],
    "current_liabilities": ["LiabilitiesCurrent"],
    "stockholders_equity": [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    ],
    "cash": [
        "CashAndCashEquivalentsAtCarryingValue",
        "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
    ],
    "long_term_debt": ["LongTermDebtNoncurrent", "LongTermDebt"],
    "current_debt": ["LongTermDebtCurrent", "DebtCurrent", "ShortTermBorrowings"],
    "operating_cash_flow": [
        "NetCashProvidedByUsedInOperatingActivities",
        "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations",
    ],
    "interest_expense": ["InterestExpense", "InterestExpenseNonoperating"],
    "depreciation_amortization": [
        "DepreciationDepletionAndAmortization",
        "DepreciationAmortizationAndAccretionNet",
        "DepreciationAndAmortization",
    ],
    "capex": [
        "PaymentsToAcquirePropertyPlantAndEquipment",
        "PaymentsToAcquireProductiveAssets",
    ],
}

_TAG_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,119}$")
_ANNUAL_FORMS = ("10-K", "10-K/A")


def get_company_facts(cik10: str) -> dict:
    """Raw companyfacts blob for a filer — one HTTP call, then cached."""
    return _get_json(f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik10}.json")


def _fiscal_year_index(facts: dict) -> dict[str, int]:
    """
    Learn the filer's OWN fiscal-year labels from its filings.

    A 10-K's XBRL facts all carry the *report's* fy/fp (so FY2024's 10-K tags its
    FY2023 comparative as fy=2024 too). Within one accession, the fact with the
    latest period end IS the report's own year — so that period end maps to that
    fy label. Doing this across every accession gives us period_end -> fiscal
    year, which then labels the comparative facts correctly too.

    This matters because the naive `end.year` convention is wrong for retailers
    with January/February year ends.
    """
    by_accn: dict[str, tuple[str, int]] = {}
    for tag_data in facts.get("facts", {}).get("us-gaap", {}).values():
        for unit_facts in tag_data.get("units", {}).values():
            for f in unit_facts:
                if f.get("form") not in _ANNUAL_FORMS or f.get("fp") != "FY":
                    continue
                accn, end, fy = f.get("accn"), f.get("end"), f.get("fy")
                if not accn or not end or fy is None:
                    continue
                prev = by_accn.get(accn)
                if prev is None or end > prev[0]:
                    by_accn[accn] = (end, fy)
    return {end: fy for end, fy in by_accn.values()}


def _fy_label(end: str, fy_index: dict[str, int]) -> int:
    """
    Label a period end with the filer's own fiscal-year convention.

    Direct hit when the period was some 10-K's current year. Otherwise — true of
    the oldest comparatives, which only ever appear as prior-year columns — carry
    over the offset from the nearest period we *did* learn. Target's fiscal 2009
    ended 2010-01-30, so its offset is -1; without this, `end.year` would label
    both 2009-01-31 and 2010-01-30 as "2009" and one of the two years would be
    silently dropped.
    """
    if end in fy_index:
        return fy_index[end]
    if not fy_index:
        return int(end[:4])
    from datetime import date

    def _d(s: str) -> date:
        return date.fromisoformat(s)

    try:
        target = _d(end)
        nearest_end, nearest_fy = min(
            fy_index.items(), key=lambda kv: abs((_d(kv[0]) - target).days))
    except (TypeError, ValueError):
        return int(end[:4])
    return int(end[:4]) + (nearest_fy - int(nearest_end[:4]))


def _is_annual_duration(f: dict) -> bool:
    """Keep full-year duration facts; drop quarterly slices tagged inside a 10-K."""
    start, end = f.get("start"), f.get("end")
    if not start:
        return True  # instant fact (balance sheet) — no duration to check
    try:
        from datetime import date
        s = date.fromisoformat(start)
        e = date.fromisoformat(end)
    except (TypeError, ValueError):
        return True
    return 340 <= (e - s).days <= 400


def _preferred_unit(units: dict[str, list]) -> Optional[str]:
    """Prefer USD; otherwise the unit with the most observations. We never mix."""
    if not units:
        return None
    if "USD" in units:
        return "USD"
    return max(units, key=lambda u: len(units[u]))


def annual_series(facts: dict, cik: int, tag: str,
                  fy_index: Optional[dict[str, int]] = None) -> list[SourcedValue]:
    """
    The clean annual series for one XBRL tag, straight out of the companyfacts
    blob. Includes prior-year comparatives carried inside later 10-Ks, which is
    how we get 5+ years of history without 5 separate filings.
    """
    tag_data = facts.get("facts", {}).get("us-gaap", {}).get(tag)
    if not tag_data:
        return []
    units = tag_data.get("units", {})
    unit = _preferred_unit(units)
    if unit is None:
        return []
    if fy_index is None:
        fy_index = _fiscal_year_index(facts)

    # period_end -> every filing that reported it, so we can detect restatements.
    per_period: dict[str, list[dict]] = {}
    for f in units[unit]:
        if f.get("form") not in _ANNUAL_FORMS or f.get("fp") != "FY":
            continue
        if not f.get("end") or f.get("val") is None:
            continue
        if not _is_annual_duration(f):
            continue
        per_period.setdefault(f["end"], []).append(f)

    by_year: dict[int, SourcedValue] = {}
    for end, observations in per_period.items():
        observations.sort(key=lambda f: (f.get("filed") or "", f.get("accn") or ""))
        first, last = observations[0], observations[-1]
        chosen = last if RESTATEMENT_POLICY == "as_last_reported" else first
        restated = first.get("val") != last.get("val")
        sv = SourcedValue(
            value=chosen.get("val"),
            unit=unit,
            period_end=end,
            fiscal_year=_fy_label(end, fy_index),
            fiscal_period="FY",
            form=chosen.get("form"),
            accession=chosen.get("accn"),
            source_url=_filing_index_url(cik, chosen.get("accn", "")),
            xbrl_tag=tag,
            filed=chosen.get("filed"),
            restated=restated,
            originally_reported=first.get("val") if restated else None,
        )
        # Belt and braces: if two period ends still land on the same label,
        # keep the later-ending one rather than letting a year vanish.
        prior = by_year.get(sv.fiscal_year)
        if prior is None or (sv.period_end or "") > (prior.period_end or ""):
            by_year[sv.fiscal_year] = sv
    return [by_year[k] for k in sorted(by_year)]


def merged_series(facts: dict, cik: int, tags: list[str],
                  fy_index: Optional[dict[str, int]] = None
                  ) -> tuple[list[SourcedValue], list[str]]:
    """
    Merge candidate tags into ONE series, per fiscal year, honouring tag
    priority. Returns (series, tags_actually_used).

    This is the fix for the truncation bug: a filer that used `Revenues` through
    FY2018 and `RevenueFromContractWithCustomerExcludingAssessedTax` from FY2019
    now yields a complete series instead of whichever half came first.
    """
    if fy_index is None:
        fy_index = _fiscal_year_index(facts)
    by_year: dict[int, SourcedValue] = {}
    used: list[str] = []
    for tag in tags:  # highest preference first
        series = annual_series(facts, cik, tag, fy_index)
        if not series:
            continue
        contributed = False
        for sv in series:
            fy = sv.fiscal_year
            if fy is None or fy in by_year:
                continue  # a higher-priority tag already covers this year
            by_year[fy] = sv
            contributed = True
        if contributed:
            used.append(tag)
    return [by_year[k] for k in sorted(by_year)], used


def get_financial_concept(query: str, metric_or_tag: str, years: int = 6) -> dict:
    """
    Escape-hatch / flexibility tool: return the annual series for either a
    friendly metric name (see CONCEPT_MAP) or a raw US-GAAP tag.
    """
    _validate_years(years)
    comp = _resolve_cik(query)
    candidates = CONCEPT_MAP.get(metric_or_tag)
    if candidates is None:
        if not _TAG_RE.match(metric_or_tag):
            raise InvalidTag(
                f"'{metric_or_tag}' is neither a known metric name "
                f"({', '.join(sorted(CONCEPT_MAP))}) nor a valid US-GAAP tag."
            )
        candidates = [metric_or_tag]

    facts = get_company_facts(comp["cik10"])
    series, used = merged_series(facts, comp["cik"], candidates)
    if not series:
        # Success with a structured absence, not an error: EDGAR answered, and
        # the answer was "this filer does not report that". `note` stays for
        # backward compatibility; `absence` is the machine-readable form.
        return {
            "company": comp,
            "metric": metric_or_tag,
            "tags_tried": candidates,
            "series": [],
            "absence": _absence("TAG_NOT_REPORTED", candidates),
            "note": f"No annual data found for '{metric_or_tag}' "
                    f"(tried tags: {', '.join(candidates)}).",
        }
    series = series[-years:]
    return {
        "company": comp,
        "metric": metric_or_tag,
        "xbrl_tags_used": used,
        "mixed_tag_basis": len(used) > 1,
        "tags_tried": candidates,
        "series": [sv.to_dict() for sv in series],
    }


# --------------------------------------------------------------------------- #
# Structured absence
# --------------------------------------------------------------------------- #
#
# One rule, applied everywhere:
#
#   Reaching EDGAR and getting a valid answer of "nothing" is a SUCCESS with an
#   explicit, structured absence. Only failing to OBTAIN an answer is an error.
#
# Before this, the same condition produced four different shapes depending on
# which tool you asked. The worst was get_key_financials handing back a bare
# `[]` for an untagged line item with no explanation anywhere in the payload:
# screening AMD returned "total_liabilities": [] and a reader could not tell
# "this filer does not tag it" from "our fetch failed". compute_screening_metrics
# listed it under data_quality.missing_line_items, but the tool one level down
# gave you nothing.
#
# This makes gaps legible. It does not fill them — invariant 7 still holds:
# missing data is reported, never estimated.

_MAX_YEARS = 25  # EDGAR's XBRL era starts ~2009; beyond this there is nothing to fetch.


def _validate_years(years: int, *, maximum: int = _MAX_YEARS) -> int:
    """Reject a nonsense window before it produces a confidently wrong answer.

    This is not defensive padding. `years=-5` produced an empty fiscal-year
    window, which tripped the same "nothing found" branch as a genuine IFRS
    filer — so asking for Apple with a negative window returned *"No XBRL
    financial data found for Apple Inc. Foreign or non-standard filers (20-F /
    IFRS) may not report US-GAAP XBRL facts."* Apple reports XBRL exhaustively.
    The tool blamed the filer for the caller's mistake, which is precisely the
    plausible-but-wrong failure this codebase exists to avoid.
    """
    if not isinstance(years, int) or isinstance(years, bool):
        raise InvalidArgument(f"`years` must be an integer, got {type(years).__name__}.")
    if years < 1:
        raise InvalidArgument(
            f"`years` must be at least 1, got {years}. A non-positive window "
            "yields no fiscal years, which is not the same as the filer having "
            "no data."
        )
    if years > maximum:
        raise InvalidArgument(
            f"`years` must be at most {maximum}, got {years}. EDGAR's XBRL era "
            "begins around 2009, so a longer window cannot return more."
        )
    return years


def _validate_limit(limit: int, *, maximum: int = 100) -> int:
    """Same reasoning as `_validate_years`, for filing-list pagination."""
    if not isinstance(limit, int) or isinstance(limit, bool):
        raise InvalidArgument(f"`limit` must be an integer, got {type(limit).__name__}.")
    if limit < 1:
        raise InvalidArgument(f"`limit` must be at least 1, got {limit}.")
    if limit > maximum:
        raise InvalidArgument(f"`limit` must be at most {maximum}, got {limit}.")
    return limit


ABSENCE_CODES = {
    "TAG_NOT_REPORTED": "The filer has never reported any of the candidate tags.",
    "TAG_DISCONTINUED": "The filer reported this once but stopped before the "
                        "reference fiscal year, so using it would pair a stale "
                        "numerator with a current denominator.",
    "OUTSIDE_WINDOW": "Reported, but only outside the requested fiscal-year window.",
}


def _absence(code: str, tags_tried: list[str], *,
             last_reported: Optional[int] = None,
             reference_fiscal_year: Optional[int] = None) -> dict:
    """Describe *why* a series is empty, in a shape every tool shares."""
    note = ABSENCE_CODES.get(code, "")
    if code == "TAG_DISCONTINUED" and last_reported:
        note = (f"Last reported for fiscal {last_reported}; the screen is anchored "
                f"to {reference_fiscal_year}. Excluded rather than carried forward.")
    return {
        "code": code,
        "tags_tried": tags_tried,
        "last_reported_fiscal_year": last_reported,
        "note": note,
    }


def _classify_absence(metric: str, tags_tried: list[str],
                      full_series: list, reference_fy: Optional[int]) -> dict:
    """Work out which kind of nothing this is.

    `full_series` is the unwindowed series — the distinction between "never
    reported" and "reported, then abandoned" is only visible before windowing,
    and it is the distinction a reader most needs.
    """
    if not full_series:
        return _absence("TAG_NOT_REPORTED", tags_tried)
    years = [sv.fiscal_year for sv in full_series if sv.fiscal_year is not None]
    last = max(years) if years else None
    if last is not None and reference_fy is not None and last < reference_fy:
        return _absence("TAG_DISCONTINUED", tags_tried, last_reported=last,
                        reference_fiscal_year=reference_fy)
    return _absence("OUTSIDE_WINDOW", tags_tried, last_reported=last,
                    reference_fiscal_year=reference_fy)


# The line items that define "which fiscal year is this screen about".
_ANCHOR_ITEMS = ("revenue", "total_assets", "net_income", "operating_income")


def _all_line_items(query: str, years: int
                    ) -> tuple[dict, dict[str, list[SourcedValue]],
                               dict[str, list[str]], Optional[int],
                               dict[str, list[SourcedValue]]]:
    """
    Fetch every CONCEPT_MAP line item from a single companyfacts call, then
    window every series to the SAME fiscal-year range.

    Windowing by fiscal year rather than by `series[-years:]` matters more than it
    looks: filers abandon tags. Target stopped tagging `GrossProfit` after FY2017,
    so a positional slice hands back FY2013-FY2017 gross profit sitting next to
    FY2021-FY2025 revenue — and the last item of each list is then silently
    combined into a margin spanning eight years. Anchoring to a reference year
    turns that into an honest gap.
    """
    comp = _resolve_cik(query)
    facts = get_company_facts(comp["cik10"])
    fy_index = _fiscal_year_index(facts)

    full: dict[str, list[SourcedValue]] = {}
    tags_used: dict[str, list[str]] = {}
    for metric, tags in CONCEPT_MAP.items():
        series, used = merged_series(facts, comp["cik"], tags, fy_index)
        full[metric] = series
        tags_used[metric] = used

    anchor_years = [sv.fiscal_year for m in _ANCHOR_ITEMS for sv in full.get(m, [])
                    if sv.fiscal_year is not None]
    all_years = [sv.fiscal_year for s in full.values() for sv in s
                 if sv.fiscal_year is not None]
    reference_fy = max(anchor_years) if anchor_years else (
        max(all_years) if all_years else None)

    if reference_fy is None:
        return comp, full, tags_used, None, full
    floor = reference_fy - years + 1
    windowed = {
        metric: [sv for sv in series
                 if sv.fiscal_year is not None and floor <= sv.fiscal_year <= reference_fy]
        for metric, series in full.items()
    }
    return comp, windowed, tags_used, reference_fy, full


def get_key_financials(query: str, years: int = 5) -> dict:
    """
    Curated multi-year financials across income statement, balance sheet and
    cash flow. Every value is a SourcedValue (period + form + accession + URL).
    """
    _validate_years(years)
    comp, series_map, tags_used, reference_fy, full = _all_line_items(query, years)
    if not any(series_map.values()):
        raise NoXBRLData(
            f"No XBRL financial data found for {comp['name']} "
            f"(CIK {comp['cik']}). Foreign or non-standard filers (20-F / IFRS) "
            "may not report US-GAAP XBRL facts."
        )
    mixed = sorted(m for m, used in tags_used.items() if len(used) > 1)

    # Every empty line item gets a reason. Without this the caller sees a bare
    # `[]` and cannot distinguish an untagged concept from a failed fetch — which
    # is exactly what screening AMD produced for total_liabilities.
    absent = {
        metric: _classify_absence(metric, CONCEPT_MAP.get(metric, []),
                                  full.get(metric, []), reference_fy)
        for metric, series in series_map.items() if not series
    }

    result = {
        "company": comp,
        "years_requested": years,
        "reference_fiscal_year": reference_fy,
        "restatement_policy": RESTATEMENT_POLICY,
        "xbrl_tags_used": {m: u for m, u in tags_used.items() if u},
        "mixed_tag_basis": mixed,
        "line_items": {
            metric: [sv.to_dict() for sv in series]
            for metric, series in series_map.items()
        },
    }
    if absent:
        result["absent_line_items"] = absent
        result["absence_note"] = (
            f"{len(absent)} of {len(series_map)} line items are empty. Each is "
            "explained in `absent_line_items` with the tags tried and why nothing "
            "was usable. These are gaps in the filer's XBRL, not fetch failures — "
            "report them as gaps and do not estimate around them."
        )
    return result


# --------------------------------------------------------------------------- #
# Screening metrics — computed in Python, with meaningfulness decided in code
# --------------------------------------------------------------------------- #

def _latest(series: list[SourcedValue]) -> Optional[SourcedValue]:
    return series[-1] if series else None


def _at(series: list[SourcedValue], fy: Optional[int]) -> Optional[SourcedValue]:
    """The value for one exact fiscal year — never a stale neighbour."""
    if fy is None:
        return None
    for sv in series:
        if sv.fiscal_year == fy:
            return sv
    return None


def _guarded_ratio(numer: Optional[float], denom: Optional[float]
                   ) -> tuple[Optional[float], bool, Optional[str]]:
    """
    Divide, and say whether the answer means anything.

    A ratio can be arithmetically perfect and analytically worthless — debt/equity
    on a company with a $2m stockholders' deficit produces -417x, which reads as
    a number but is really the sentence "equity is negative". Deciding that in
    code (not in a prompt) is what makes the output trustworthy.
    """
    if numer is None or denom is None:
        return None, False, "input not reported"
    if denom == 0:
        return None, False, "denominator is zero"
    value = numer / denom
    if denom < 0:
        return value, False, (
            "denominator is negative — the ratio is not interpretable; "
            "report the negative balance itself instead"
        )
    if abs(denom) < abs(numer) * THRESHOLDS["near_zero_denominator_ratio"]:
        return value, False, (
            "denominator is near zero relative to the numerator — "
            "the ratio is unstable and should not be quoted"
        )
    return value, True, None


def _metric(value, unit, inputs, meaningful=True, caveat=None, **extra) -> dict:
    out = {
        "value": value,
        "unit": unit,
        "meaningful": meaningful,
        "caveat": caveat,
        "inputs": [x.to_dict() for x in inputs if x],
    }
    out.update(extra)
    return out


def _today():
    """Indirection so tests can freeze 'now' — staleness is time-dependent, and a
    test that starts failing next winter is worse than no test."""
    from datetime import date
    return date.today()


def _months_since(period_end: Optional[str]) -> Optional[float]:
    if not period_end:
        return None
    try:
        from datetime import date
        end = date.fromisoformat(period_end)
    except (TypeError, ValueError):
        return None
    return (_today() - end).days / 30.44


FLAG_CATALOGUE: dict[str, dict[str, str]] = {
    # --- high: a reason to stop and think before spending more time ---
    "NEGATIVE_EQUITY": {
        "severity": "high",
        "fires_when": "Stockholders' equity is below zero.",
        "why": "Ratios that divide by equity stop being interpretable, and it is a "
               "capital-structure issue in its own right.",
    },
    "EARNINGS_QUALITY": {
        "severity": "high",
        "fires_when": "Net income is positive while operating income is negative.",
        "why": "Profit is coming from outside the operating business. The gap has to "
               "be identified before the company can be called profitable.",
    },
    "LIQUIDITY": {
        "severity": "high",
        "fires_when": "Current ratio is below the `current_ratio_low` threshold.",
        "why": "Current liabilities exceed current assets. Structural for some "
               "retailers, so read it against the sector before calling it distress.",
    },
    "LEVERAGE": {
        "severity": "high",
        "fires_when": "Debt/EBITDA exceeds the `debt_to_ebitda_high` threshold.",
        "why": "Constrains what an acquirer can do with the existing capital structure.",
    },
    "COVERAGE": {
        "severity": "high",
        "fires_when": "Interest coverage is below the `interest_coverage_low` threshold.",
        "why": "Operating earnings are thin relative to interest owed.",
    },
    "NEGATIVE_EBITDA": {
        "severity": "high",
        "fires_when": "The EBITDA proxy is negative.",
        "why": "Any multiple built on it is meaningless, so leverage cannot be read "
               "the usual way.",
    },
    # --- medium: worth a paragraph in the memo ---
    "REVENUE_DECLINE": {
        "severity": "medium",
        "fires_when": "Year-over-year revenue change is below `revenue_decline_pct`.",
        "why": "Direction matters more than level in a first-pass screen.",
    },
    "CASH_BURN": {
        "severity": "medium",
        "fires_when": "Operating cash flow is negative in the reference year.",
        "why": "The business consumed cash rather than generating it.",
    },
    "STALE_DATA": {
        "severity": "medium",
        "fires_when": "The latest annual period end is older than `stale_data_months`.",
        "why": "The screen may predate a material change; check for a recent filing.",
    },
    # --- info: data-quality caveats, not findings about the business ---
    "MISSING_DATA": {
        "severity": "info",
        "fires_when": "One or more curated line items are not tagged by this filer.",
        "why": "Named rather than estimated. See `absent_line_items` for which and why.",
    },
    "TAG_DISCONTINUED": {
        "severity": "info",
        "fires_when": "A filer stopped tagging a concept before the reference year.",
        "why": "Excluded rather than carried forward, which would pair a stale "
               "numerator with a current denominator.",
    },
    "MIXED_TAG_BASIS": {
        "severity": "info",
        "fires_when": "A series was assembled across more than one US-GAAP tag.",
        "why": "Usually comparable, but ASC 606 sometimes changed the number and not "
               "just the label, so a long trend deserves a spot-check.",
    },
    "RESTATED": {
        "severity": "info",
        "fires_when": "A period's value differs from what an earlier filing reported.",
        "why": "The figure shown is as-last-reported; the change is auditable rather "
               "than invisible.",
    },
}


def _detect_flags(metrics: dict, vals: dict, svs: dict,
                  latest_period_end: Optional[str],
                  mixed: list[str], restated: list[str],
                  stale_items: Optional[dict[str, int]] = None) -> list[dict]:
    """
    Red flags, decided here. Each is {code, severity, message, evidence}.

    The model's job is to narrate these; it is not asked to spot them. That
    boundary is the whole trust argument: an analyst can re-run this function
    and get the same flags every time, which is not true of a prompt.
    """
    flags: list[dict] = []

    def add(code, severity, message, evidence=()):
        # Severity comes from FLAG_CATALOGUE, not from the call site, so the
        # catalogue exposed as an MCP resource cannot drift from the behaviour --
        # there is exactly one place a severity is written down. An unknown code
        # raises KeyError, which is correct: it is a programming error.
        flags.append({
            "code": code,
            "severity": FLAG_CATALOGUE[code]["severity"],
            "message": message,
            "evidence": [sv.to_dict() for sv in evidence if sv],
        })

    eq, oi, ni = vals.get("stockholders_equity"), vals.get("operating_income"), vals.get("net_income")
    ocf, ebitda = vals.get("operating_cash_flow"), vals.get("ebitda")

    if eq is not None and eq < 0:
        add("NEGATIVE_EQUITY", "high",
            f"Stockholders' equity is negative ({eq:,.0f}). Leverage ratios that "
            "divide by equity are not meaningful; treat this as a capital-structure "
            "issue in its own right.",
            [svs.get("stockholders_equity")])

    if ni is not None and oi is not None and ni > 0 and oi < 0:
        add("EARNINGS_QUALITY", "high",
            f"Net income is positive ({ni:,.0f}) while operating income is negative "
            f"({oi:,.0f}) — roughly {ni - oi:,.0f} of profit comes from outside the "
            "operating business. Identify the non-operating item before treating "
            "this company as profitable.",
            [svs.get("net_income"), svs.get("operating_income")])

    cr = metrics.get("current_ratio")
    if cr and cr.get("meaningful") and cr["value"] is not None \
            and cr["value"] < THRESHOLDS["current_ratio_low"]:
        add("LIQUIDITY", "high",
            f"Current ratio is {cr['value']:.2f} (below "
            f"{THRESHOLDS['current_ratio_low']:.1f}) — current liabilities exceed "
            "current assets.", [svs.get("current_assets"), svs.get("current_liabilities")])

    de = metrics.get("debt_to_ebitda")
    if de and de.get("meaningful") and de["value"] is not None \
            and de["value"] > THRESHOLDS["debt_to_ebitda_high"]:
        add("LEVERAGE", "high",
            f"Debt/EBITDA is {de['value']:.1f}x, above the "
            f"{THRESHOLDS['debt_to_ebitda_high']:.0f}x screening threshold.",
            [svs.get("long_term_debt"), svs.get("current_debt")])

    ic = metrics.get("interest_coverage")
    if ic and ic.get("meaningful") and ic["value"] is not None \
            and ic["value"] < THRESHOLDS["interest_coverage_low"]:
        add("COVERAGE", "high",
            f"Interest coverage is {ic['value']:.1f}x, below "
            f"{THRESHOLDS['interest_coverage_low']:.0f}x.",
            [svs.get("operating_income"), svs.get("interest_expense")])

    if ebitda is not None and ebitda < 0:
        add("NEGATIVE_EBITDA", "high",
            f"EBITDA is negative ({ebitda:,.0f}); leverage multiples built on it "
            "are not meaningful.",
            [svs.get("operating_income"), svs.get("depreciation_amortization")])

    yoy = metrics.get("revenue_yoy")
    if yoy and yoy["value"] is not None and yoy["value"] < THRESHOLDS["revenue_decline_pct"]:
        add("REVENUE_DECLINE", "medium",
            f"Revenue fell {abs(yoy['value']) * 100:.1f}% year over year.",
            [svs.get("revenue")])

    if ocf is not None and ocf < 0:
        add("CASH_BURN", "medium",
            f"Operating cash flow is negative ({ocf:,.0f}) in the latest fiscal year.",
            [svs.get("operating_cash_flow")])

    months = _months_since(latest_period_end)
    if months is not None and months > THRESHOLDS["stale_data_months"]:
        add("STALE_DATA", "medium",
            f"The most recent annual figures are ~{months:.0f} months old "
            f"(period ended {latest_period_end}). Check for a more recent 10-Q "
            "before relying on this screen.")

    missing = [m for m in ("revenue", "operating_income", "total_assets",
                           "stockholders_equity") if vals.get(m) is None]
    if missing:
        add("MISSING_DATA", "info",
            "Not reported in XBRL for the reference fiscal year: " +
            ", ".join(missing) + ". These are absent, not zero.")

    if stale_items:
        add("TAG_DISCONTINUED", "info",
            "The filer stopped tagging these before the reference year, so they "
            "are excluded rather than carried forward: " +
            ", ".join(f"{m} (last seen FY{fy})" for m, fy in sorted(stale_items.items()))
            + ".")

    if mixed:
        add("MIXED_TAG_BASIS", "info",
            "Series stitched across more than one US-GAAP tag (the filer changed "
            "tagging mid-history): " + ", ".join(mixed) +
            ". Comparability across years is usually fine but worth a spot-check.")

    if restated:
        add("RESTATED", "info",
            "A later filing reported a different value for a prior period: " +
            ", ".join(restated) + f". Policy in force: {RESTATEMENT_POLICY}.")

    return flags


def compute_screening_metrics(query: str, years: int = 5) -> dict:
    """
    The full screen result: growth, margins, leverage, liquidity — arithmetic done
    here in code — plus code-detected red flags and a data-quality summary. Each
    metric carries the sourced inputs it was computed from and a `meaningful`
    boolean, so the caller never has to decide whether a ratio is quotable.
    """
    _validate_years(years)
    comp, s, tags_used, reference_fy, full = _all_line_items(query, years)
    if not any(s.values()) or reference_fy is None:
        raise NoXBRLData(
            f"No XBRL financial data found for {comp['name']} (CIK {comp['cik']})."
        )

    # Everything below is pinned to ONE fiscal year. A line item the filer
    # stopped tagging is absent, not backfilled from an older year.
    svs: dict[str, Optional[SourcedValue]] = {m: _at(v, reference_fy) for m, v in s.items()}
    vals: dict[str, Optional[float]] = {
        m: (sv.value if sv else None) for m, sv in svs.items()
    }
    # Line items the filer once tagged and later abandoned. Reported as a gap,
    # never carried forward into the reference year.
    stale_items = {
        m: _latest(v).fiscal_year
        for m, v in full.items()
        if svs.get(m) is None and v and _latest(v).fiscal_year is not None
    }

    # Guard against mixing currencies in a single ratio.
    units = {sv.unit for sv in svs.values() if sv and sv.value is not None}
    monetary_units = {u for u in units if u != "pure"}
    single_currency = len(monetary_units) <= 1
    currency = next(iter(monetary_units), "USD")

    metrics: dict[str, dict] = {}
    rev_series = s.get("revenue", [])

    # --- Growth -----------------------------------------------------------
    last = _at(rev_series, reference_fy)
    if last is not None and len(rev_series) >= 2:
        first = rev_series[0]
        n = (last.fiscal_year or 0) - (first.fiscal_year or 0)
        cagr = None
        if first.value and last.value and first.value > 0 and last.value > 0 and n > 0:
            cagr = (last.value / first.value) ** (1 / n) - 1
        metrics["revenue_cagr"] = _metric(
            cagr, "ratio", [first, last], meaningful=cagr is not None,
            caveat=None if cagr is not None else "needs positive revenue in both years",
            window=f"FY{first.fiscal_year}-FY{last.fiscal_year}")
        prior = _at(rev_series, reference_fy - 1)
        if prior is not None:
            yoy, ok, caveat = _guarded_ratio(
                (last.value - prior.value)
                if (last.value is not None and prior.value is not None) else None,
                prior.value)
            metrics["revenue_yoy"] = _metric(yoy, "ratio", [prior, last], ok, caveat)

    # --- Margins (latest FY) ---------------------------------------------
    rev = vals.get("revenue")
    gp, gp_sv = vals.get("gross_profit"), svs.get("gross_profit")
    if gp is None and rev is not None and vals.get("cost_of_revenue") is not None:
        gp = rev - vals["cost_of_revenue"]           # derive when not tagged
        gp_sv = svs.get("cost_of_revenue")
    oi, ni = vals.get("operating_income"), vals.get("net_income")

    for name, numer, numer_sv in (
        ("gross_margin", gp, gp_sv),
        ("operating_margin", oi, svs.get("operating_income")),
        ("net_margin", ni, svs.get("net_income")),
    ):
        if numer is None or rev is None:
            continue
        value, ok, caveat = _guarded_ratio(numer, rev)
        metrics[name] = _metric(value, "ratio", [numer_sv, svs.get("revenue")], ok, caveat)

    # --- Leverage ---------------------------------------------------------
    ltd, cd = vals.get("long_term_debt"), vals.get("current_debt")
    debt_inputs = [svs.get("long_term_debt"), svs.get("current_debt")]
    total_debt = None
    if ltd is not None or cd is not None:
        total_debt = (ltd or 0) + (cd or 0)
        metrics["total_debt"] = _metric(
            total_debt, currency, debt_inputs,
            caveat=("approximated as long-term + current debt tags; finance leases "
                    "and other debt-like items are not fully assembled"))

    da = vals.get("depreciation_amortization")
    ebitda = (oi + da) if (oi is not None and da is not None) else None
    if ebitda is not None:
        metrics["ebitda"] = _metric(
            ebitda, currency,
            [svs.get("operating_income"), svs.get("depreciation_amortization")],
            caveat="EBITDA proxied as operating income + D&A")
    vals["ebitda"] = ebitda

    if total_debt is not None:
        value, ok, caveat = _guarded_ratio(total_debt, vals.get("stockholders_equity"))
        metrics["debt_to_equity"] = _metric(
            value, "x", debt_inputs + [svs.get("stockholders_equity")], ok, caveat)
        if ebitda is not None:
            value, ok, caveat = _guarded_ratio(total_debt, ebitda)
            if ebitda < 0:
                ok, caveat = False, "EBITDA is negative — the multiple is not meaningful"
            metrics["debt_to_ebitda"] = _metric(
                value, "x", debt_inputs + [svs.get("operating_income")], ok, caveat)

    # --- Liquidity / coverage --------------------------------------------
    value, ok, caveat = _guarded_ratio(vals.get("current_assets"), vals.get("current_liabilities"))
    if value is not None:
        metrics["current_ratio"] = _metric(
            value, "x", [svs.get("current_assets"), svs.get("current_liabilities")], ok, caveat)

    value, ok, caveat = _guarded_ratio(oi, vals.get("interest_expense"))
    if value is not None:
        metrics["interest_coverage"] = _metric(
            value, "x", [svs.get("operating_income"), svs.get("interest_expense")], ok, caveat)
        if oi is not None and oi < 0:
            metrics["interest_coverage"]["meaningful"] = False
            metrics["interest_coverage"]["caveat"] = (
                "operating income is negative — there are no operating earnings to "
                "cover interest")

    if vals.get("operating_cash_flow") is not None:
        metrics["operating_cash_flow_latest"] = _metric(
            vals["operating_cash_flow"], currency, [svs.get("operating_cash_flow")])

    if not single_currency:
        for m in metrics.values():
            m["meaningful"] = False
            m["caveat"] = (m.get("caveat") or "") + \
                " | line items are reported in more than one currency; ratios are unsafe"

    mixed = sorted(m for m, used in tags_used.items() if len(used) > 1)
    restated = sorted(m for m, sv in svs.items() if sv and sv.restated)
    anchor = svs.get("revenue") or svs.get("total_assets")
    latest_period_end = anchor.period_end if anchor else None

    flags = _detect_flags(metrics, vals, svs, latest_period_end, mixed, restated,
                          stale_items)

    return {
        "company": comp,
        "as_of_fiscal_year": reference_fy,
        "as_of_period_end": latest_period_end,
        "currency": currency,
        "metrics": metrics,
        "flags": flags,
        "data_quality": {
            "mixed_tag_basis": mixed,
            "restated_line_items": restated,
            "missing_line_items": sorted(m for m, v in vals.items()
                                         if v is None and m != "ebitda"),
            "last_reported_before_reference_year": stale_items,
            "restatement_policy": RESTATEMENT_POLICY,
            "single_currency": single_currency,
        },
        "thresholds": THRESHOLDS,
        "note": "All ratios computed in code from the sourced inputs listed on each "
                "metric. A metric with meaningful=false must NOT be quoted as a "
                "figure — state its caveat instead. Missing metrics mean the "
                "underlying tag was not reported, not that the value is zero.",
    }


# --------------------------------------------------------------------------- #
# Filings list (attribution + document access)
# --------------------------------------------------------------------------- #

def list_filings(query: str, form_types: Optional[list[str]] = None,
                 limit: int = 15) -> dict:
    _validate_limit(limit)
    comp = _resolve_cik(query)
    subs = _get_submissions(comp["cik10"])
    recent = subs.get("filings", {}).get("recent", {})
    forms = recent.get("form", [])
    wanted = {f.upper() for f in form_types} if form_types else None

    results = []
    for i in range(len(forms)):
        if wanted and forms[i].upper() not in wanted:
            continue
        accn = recent["accessionNumber"][i]
        results.append({
            "form": forms[i],
            "filed": recent["filingDate"][i],
            "period": recent["reportDate"][i],
            "accession": accn,
            "primary_document": recent["primaryDocument"][i],
            "url": _document_url(comp["cik"], accn, recent["primaryDocument"][i]),
            "index_url": _filing_index_url(comp["cik"], accn),
        })
        if len(results) >= limit:
            break
    return {"company": comp, "count": len(results), "filings": results}


# --------------------------------------------------------------------------- #
# Disclosure signals (EDGAR full-text search)
# --------------------------------------------------------------------------- #
#
# The XBRL side of this client answers "what are the numbers". It cannot answer
# "what is the company worried about" — going-concern doubt, a material weakness,
# a covenant waiver and customer concentration are sentences, and no tag exposes
# them. For a distress screen those disclosures matter more than any ratio.
#
# Two things make this more than a search box:
#
# 1. The phrasing is curated. A model asked to "search for risks" invents
#    plausible queries and misses the terms of art. An auditor writes "substantial
#    doubt about its ability to continue as a going concern", never "may go
#    bankrupt". The packs encode the language that actually appears in filings.
#
# 2. The boilerplate call is computed, not narrated. A phrase hit does NOT mean
#    the condition applies — risk-factor sections describe hypothetical material
#    weaknesses in the same words an auditor uses to report a real one. Beyond
#    Meat matches "material weakness ..." in all seven of its 10-Ks while its
#    Item 9A concludes controls were effective; every hit is the auditor
#    describing its own testing methodology. So we compare the filings that
#    matched against the filings that *could* have matched: language present in
#    every annual report is standing boilerplate, language that appears in some
#    years and not others is a change worth reading. That comparison is a rule,
#    so it belongs in code, same as the ratio flags.

_EFTS_URL = "https://efts.sec.gov/LATEST/search-index"

# EDGAR's full-text index does not reach back further than this.
FULL_TEXT_COVERAGE_FROM = "2001"

# Phrases are calibrated, not guessed. Each was measured against three filers --
# Beyond Meat (distressed but a going concern), Target (healthy) and Aditxt (a
# real going-concern filer) -- and kept only where the counts discriminate:
#
#   phrase                        BYND   TGT   ADTX
#   "substantial doubt"              0     0    116   <- fires only when true
#   "material weakness"             25    23     24   <- fires everywhere
#   "one customer accounted for"    20     0      0   <- BYND really is concentrated
#   "goodwill impairment"            0    20      0   <- BYND carries no goodwill
#
# The long, formal versions of these phrases were the first attempt and were
# wrong: "material weakness in our internal control over financial reporting"
# matched 0 Target filings while "material weakness" matched 23. An over-specific
# phrase produces a false "absent", and "absent" is reported to the deal team as a
# real negative finding -- the most damaging error this tool could make. Phrases
# are therefore chosen for recall, and precision is recovered by the boilerplate
# classification below plus the requirement to read the filing.
DISCLOSURE_PACKS: dict[str, dict] = {
    "going_concern": {
        "phrase": "substantial doubt",
        "severity": "critical",
        "why": "The statutory trigger wording for going-concern doubt: the auditor "
               "or management doubts the company can fund twelve more months of "
               "operations. Close to disqualifying without a recapitalisation thesis.",
    },
    "material_weakness": {
        "phrase": "material weakness",
        "severity": "high",
        "why": "A control gap that could allow a material misstatement. Undermines "
               "confidence in every other number in the screen. Note that the "
               "auditor's standard report describes its own testing using this exact "
               "phrase, so this one is boilerplate far more often than not.",
    },
    "customer_concentration": {
        "phrase": "one customer accounted for",
        "severity": "medium",
        "why": "Revenue concentration is a valuation discount and a diligence "
               "workstream. Common and often decisive in lower-middle-market targets.",
    },
    "impairment": {
        "phrase": "goodwill impairment",
        "severity": "medium",
        "why": "Assets written below carrying value — often the first admission "
               "that an acquisition or a segment underperformed.",
    },
}

# Two packs were built and then removed rather than shipped, because measurement
# said they would lie:
#
#   covenant breach -- no exact phrase discriminated. "covenant violation",
#     "waiver from our lenders" and "not in compliance with the covenants" each
#     returned zero hits even for the distressed filer, while bare "covenant"
#     returned 84 (BYND) and 274 (TGT) of pure boilerplate. A pack that always
#     reports "absent" is worse than no pack, because absence is reported as a
#     finding. Covenant compliance is called out as a known gap instead.
#
#   restatement -- superseded by better evidence. compute_screening_metrics
#     already emits a RESTATED flag derived from the XBRL facts themselves, which
#     is verifiable arithmetic rather than a phrase match. Adding a fuzzy text
#     signal alongside a computed one would only invite the two to disagree.


def _efts_search(phrase: str, cik10: Optional[str] = None,
                 forms: Optional[list[str]] = None) -> dict:
    """Query EDGAR full-text search for an exact phrase."""
    from urllib.parse import urlencode

    params: dict[str, str] = {"q": f'"{phrase}"'}
    if cik10:
        params["ciks"] = cik10
    if forms:
        params["forms"] = ",".join(f.upper() for f in forms)
    return _get_json(f"{_EFTS_URL}?{urlencode(params)}")


def _hits(payload: dict) -> list[dict]:
    return payload.get("hits", {}).get("hits", [])


def _total(payload: dict) -> int:
    """EDGAR's match count. NOTE: this counts matching *documents*, not filings.

    A single 10-K is dozens of files, so a phrase in the main document plus two
    exhibits counts three. Use `_distinct_filings` whenever the number is going to
    be compared against a count of filings.
    """
    return payload.get("hits", {}).get("total", {}).get("value", 0)


def _distinct_filings(payload: dict) -> int:
    """Number of distinct filings represented in a response's hits.

    Counted from accession numbers rather than from `total`, because the two are
    in different units. Full-text search caps its hit list at 100; that ceiling is
    unreachable for a single company scoped to one form type, which is the only
    place this is used.
    """
    return len({
        hit.get("_source", {}).get("adsh") or hit.get("_id", "").split(":")[0]
        for hit in _hits(payload)
    })


def _annual_accessions(comp: dict) -> list[str]:
    """Accession numbers of the company's annual reports, newest first.

    The denominator for the boilerplate test: language in every one of these is
    standing template text, not news.
    """
    subs = _get_submissions(comp["cik10"])
    recent = subs.get("filings", {}).get("recent", {})
    return [
        recent["accessionNumber"][i]
        for i, form in enumerate(recent.get("form", []))
        if form in _ANNUAL_FORMS
    ]


def _classify(total_matched: int, annual_matched: int,
              annual_on_file: int) -> tuple[str, str]:
    """Decide what a set of matching filings means. Returns (assessment, note).

    Counts come from EDGAR's `total`, never from the returned hit list. Full-text
    search caps its response at 100 hits, so a filer whose language appears in
    every one of twenty filings would look partial if we counted what came back --
    which is exactly how standing boilerplate would get mistaken for a change.
    """
    if total_matched == 0:
        return ("absent", "Phrase does not appear in any filing indexed since "
                          f"{FULL_TEXT_COVERAGE_FROM}. Treat as a genuine negative "
                          "signal, not a data gap.")

    if annual_on_file >= 3 and annual_matched >= annual_on_file:
        return ("likely_boilerplate",
                f"Present in all {annual_on_file} annual reports on file. Language "
                "that never changes is almost always standing risk-factor or "
                "audit-report template text. Do not report it as a finding without "
                "reading the filing.")
    if annual_matched:
        return ("changed_over_time",
                f"Present in {annual_matched} of {annual_on_file} annual reports — "
                "the language is not constant. Language that appears or disappears "
                "between years is the higher-signal case; read the years that differ.")
    return ("present_non_annual",
            "Appears outside the annual reports (for example in an 8-K or a "
            "registration statement), which points to a discrete event rather than "
            "standing language. Read the filing.")


def _pack_result(name: str, spec: dict, comp: dict, annual_on_file: int) -> dict:
    # Two queries per signal: one unscoped for reach and examples, one scoped to
    # annual reports for the count the classification actually turns on.
    payload = _efts_search(spec["phrase"], comp["cik10"])
    annual_payload = _efts_search(spec["phrase"], comp["cik10"], forms=["10-K"])

    matched: list[dict] = []
    seen: set[str] = set()
    for hit in _hits(payload):
        source = hit.get("_source", {})
        accn = source.get("adsh") or hit.get("_id", "").split(":")[0]
        if accn in seen:
            continue
        seen.add(accn)
        matched.append({
            "accession": accn,
            "form": source.get("form"),
            "filed": source.get("file_date"),
            "url": _filing_index_url(comp["cik"], accn),
        })

    total = _total(payload)
    # Distinct filings, not `total` -- `total` counts documents, and a 10-K plus
    # two matching exhibits would otherwise read as three annual reports.
    annual_matched = min(_distinct_filings(annual_payload), annual_on_file)
    assessment, note = _classify(total, annual_matched, annual_on_file)
    return {
        "signal": name,
        "phrase": spec["phrase"],
        "severity": spec["severity"],
        "why_it_matters": spec["why"],
        "present": total > 0,
        "documents_matched": total,
        "annual_reports_matched": annual_matched,
        "annual_reports_on_file": annual_on_file,
        "assessment": assessment,
        "assessment_note": note,
        # Newest first, capped: the point is to give the model somewhere to look,
        # not to enumerate twenty years of identical risk-factor pages.
        "examples": sorted(matched, key=lambda m: m["filed"] or "", reverse=True)[:4],
    }


def scan_disclosure_signals(query: str,
                            extra_phrases: Optional[list[str]] = None) -> dict:
    """Sweep a company's filings for the disclosure language a screen turns on."""
    comp = _resolve_cik(query)
    annual_on_file = len(_annual_accessions(comp))

    signals = [_pack_result(name, spec, comp, annual_on_file)
               for name, spec in DISCLOSURE_PACKS.items()]

    for phrase in (extra_phrases or []):
        if not isinstance(phrase, str) or not phrase.strip():
            continue
        signals.append(_pack_result(
            phrase.strip(),
            {"phrase": phrase.strip(), "severity": "unrated",
             "why": "Caller-supplied phrase; no curated interpretation. Note that "
                    "an over-specific phrase yields a false 'absent'."},
            comp, annual_on_file,
        ))

    absent = [s["signal"] for s in signals if s["assessment"] == "absent"]
    worth_reading = [s["signal"] for s in signals
                     if s["assessment"] in ("changed_over_time", "present_non_annual")]

    return {
        "company": comp,
        "annual_reports_on_file": annual_on_file,
        "signals": signals,
        "summary": {
            "absent": absent,
            "worth_reading": worth_reading,
            "likely_boilerplate": [s["signal"] for s in signals
                                   if s["assessment"] == "likely_boilerplate"],
        },
        "coverage": f"EDGAR full-text search indexes filings from "
                    f"{FULL_TEXT_COVERAGE_FROM} onward only.",
        "how_to_use": (
            "`absent` signals are reportable as-is — a phrase that never appears is a "
            "real negative finding. Everything else is EVIDENCE, not a conclusion: a "
            "hit means the words are in the filing, not that the condition applies. "
            "Before reporting any present signal, read the surrounding text via "
            "get_risk_factors or the linked filing. These are deliberately NOT part "
            "of `flags` from compute_screening_metrics, which stays reserved for red "
            "flags code can verify arithmetically."
        ),
    }


# --------------------------------------------------------------------------- #
# Risk factors (Item 1A of the latest 10-K)
# --------------------------------------------------------------------------- #

def _find_latest_10k(comp: dict) -> Optional[dict]:
    subs = _get_submissions(comp["cik10"])
    recent = subs.get("filings", {}).get("recent", {})
    for i, form in enumerate(recent.get("form", [])):
        if form == "10-K":
            return {
                "accession": recent["accessionNumber"][i],
                "primary_document": recent["primaryDocument"][i],
                "filed": recent["filingDate"][i],
                "period": recent["reportDate"][i],
            }
    return None


# Section start/end markers. The end marker is the *next* item, which is what
# bounds the span. Only risk_factors is exposed as a tool today; the others cost
# nothing to carry and make the extractor testable against more real documents.
SECTION_PATTERNS: dict[str, tuple[str, str, str]] = {
    "risk_factors": (
        r"Item\s*1A[\.\s:\-–—]+Risk\s*Factors",
        r"Item\s*1B[\.\s:\-–—]+Unresolved|Item\s*2[\.\s:\-–—]+Propert",
        "Item 1A — Risk Factors",
    ),
    "mdna": (
        r"Item\s*7[\.\s:\-–—]+Management.{0,3}s\s*Discussion",
        r"Item\s*7A[\.\s:\-–—]+Quantitative",
        "Item 7 — Management's Discussion and Analysis",
    ),
    "legal_proceedings": (
        r"Item\s*3[\.\s:\-–—]+Legal\s*Proceedings",
        r"Item\s*4[\.\s:\-–—]+(Mine|Submission)",
        "Item 3 — Legal Proceedings",
    ),
    "controls": (
        r"Item\s*9A[\.\s:\-–—]+Controls\s*and\s*Procedures",
        r"Item\s*9B[\.\s:\-–—]+Other",
        "Item 9A — Controls and Procedures",
    ),
}

# A table-of-contents row with its page number runs a few dozen characters. The
# shortest real section observed is Dollar General's Item 3, a ~230-character
# cross-reference into the notes. 80 clears the former with room under the latter.
_MIN_SECTION_CHARS = 80


def _find_section_span(text: str, start_pat: str, end_pat: str
                       ) -> Optional[tuple[int, int]]:
    """Locate a section's real span in messy filing text, in two steps.

    Each marker appears several times in a 10-K: once in the table of contents,
    again in cross-references ("see Item 1A"), and once as the actual heading.
    Two obvious rules both fail on real filings:

      * *first match* lands in the table of contents;
      * *last match* — the previous implementation here — lands on a
        cross-reference that appears AFTER the section. On Dollar General's
        FY2025 10-K that returned 2,958 characters of audit-committee text
        beginning mid-sentence, and reported it as a successful extraction.

    So: the widest start/end pairing is used only to identify which *end* marker
    is real, since the real end is by construction far from every start. Given
    that end, the true heading is the last candidate before it — contents rows
    and forward-looking cross-references all sit earlier, and any cross-reference
    that sits later is now excluded by construction.

    Verified against Apple and Dollar General FY2025 10-Ks, which between them
    contain contents rows, earlier cross-references and later cross-references.
    """
    starts = [m.start() for m in re.finditer(start_pat, text, re.IGNORECASE)]
    if not starts:
        return None
    ends = [m.start() for m in re.finditer(end_pat, text, re.IGNORECASE)]

    section_end, widest = len(text), -1
    for start in starts:
        end = next((e for e in ends if e > start), len(text))
        if end - start > widest:
            widest, section_end = end - start, end

    preceding = [s for s in starts if s < section_end]
    if not preceding:
        return None
    section_start = max(preceding)

    if section_end - section_start < _MIN_SECTION_CHARS:
        return None
    return section_start, section_end


def extract_section(text: str, section: str = "risk_factors") -> Optional[str]:
    """Pure-text section extraction, split out so it is unit-testable."""
    if section not in SECTION_PATTERNS:
        raise InvalidArgument(
            f"Unknown section {section!r}. Known: {', '.join(sorted(SECTION_PATTERNS))}."
        )
    text = re.sub(r"[ \t\xa0]+", " ", text)
    text = re.sub(r"\n{2,}", "\n", text)
    start_pat, end_pat, _label = SECTION_PATTERNS[section]
    span = _find_section_span(text, start_pat, end_pat)
    if span is None:
        return None
    return text[span[0]:span[1]].strip() or None


def extract_item_1a(text: str, max_chars: int = 12000) -> Optional[str]:
    """Item 1A extraction. Kept as a named entry point; see `extract_section`.

    `max_chars` is accepted for backward compatibility but no longer bounds the
    span — truncation is the caller's decision, and silently cutting here made a
    partial section indistinguishable from a complete one.
    """
    return extract_section(text, "risk_factors")


def get_risk_factors(query: str, max_chars: int = 12000) -> dict:
    """
    Extract Item 1A "Risk Factors" from the latest 10-K. This is deliberately
    conservative: EDGAR filings are messy HTML, so if we can't confidently
    isolate the section we return the source URL for a human to verify — never a
    confident guess.
    """
    comp = _resolve_cik(query)
    k = _find_latest_10k(comp)
    if not k:
        raise SectionNotFound(
            f"No 10-K on file for {comp['name']} (CIK {comp['cik']})."
        )
    url = _document_url(comp["cik"], k["accession"], k["primary_document"])
    soup = BeautifulSoup(_get(url).text, "lxml")
    section = extract_item_1a(soup.get_text("\n"), max_chars)

    if not section:
        return {
            "company": comp, "source_url": url, "extraction": "failed",
            "risk_factors_text": None, "filing": k,
            "note": "Could not confidently isolate Item 1A from the 10-K HTML. "
                    "Open the source filing to review risk factors manually.",
        }
    return {
        "company": comp,
        "source_url": url,
        "filing": k,
        "extraction": "heading_match",
        "truncated": len(section) > max_chars,
        "risk_factors_text": section[:max_chars],
    }
